site_name: On-Demend
site_url: https://on-demend.github.io/On-Demend/
site_description: On-Demand AWS
site_author: On-Demand
repo_url: https://github.com/On-Demend/On-Demend
repo_name: On-Demend/On-Demend
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
nav:
  - "Home": index.md
  - "CI/CD":
    - "CodeSeries":
      - "CodeBuild":
          - "ECS": "CI&CD/CodeSeries/CodeBuild/ecs.md"
      - "CodeDeploy":
          - "ECS": "CI&CD/CodeSeries/CodeDeploy/ecs.md"
  - "EC2":
    - Systemd: EC2/systemd.md
  - "ECS":
    - Docker: ECS/docker.md
    - Gateway: ECS/gateway.md
    - Installation: ECS/installation.md
  - "EKS":
    - "AWS Load Balancer Controller": "EKS/awslbctr.md"
    - "Base Resources": "EKS/base_resource.md"
    - Installation: EKS/install.md
    - "Modify Domain": "EKS/change_domain.md"
  - "Logging":
    - Athena: Logging/athena.md
    - CloudWatch: Logging/cloudwatch.md
    - Fluentbit: Logging/fluentbit.md
  - "Tools":
    - "AWS-Nuke": "tools/nuke/default.md"
    - "cURL": "tools/curl.md"
    - "SSH/SCP": "tools/ssh_scp.md"
    - "Terraform": "tools/terraform.md"
  - "Getting Started":
    - "Linux":
      - "What is Linux": "tutorial/linux/what-is-linux.md"
      - "Commands": "tutorial/linux/commands.md"
      - "Exam 1": "tutorial/linux/exam.md"
      - "Exam 2": "tutorial/linux/exam2.md"
    - "Network":
      - "IP & Subnet": "tutorial/Network/IP.md"
      - "Protocols": "tutorial/Network/Protocols.md"
      - "HTTP": "tutorial/Network/HTTP.md"
theme:
  language: ko
  #custom_dir: overrides
  name: material
  logo: "logos/on-demend.png"
  favicon: "logos/on-demend.png"
  icon:
    repo: fontawesome/brands/github
  font:
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 라이트 모드로 전환

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: 다크 모드로 전환

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: 시스템 설정 모드로 전환

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.follow
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.tracking
    - search.share
    - navigation.footer
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - tags:
      enabled: true
      listings: false
  - meta
  - git-committers:
      repository: On-Demend/On-Demend
      branch: main
  - git-authors

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: Copyright &copy; 2025 On-Demend
extra:
  generator: false
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/On-Demend
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/u/ondemend?_gl=1*6ghh16*_gcl_au*MTM4OTg1NzU2NC4xNzQ0OTU0NTc1*_ga*MzA1OTk1NTExLjE3NDQ5NTQ1NzY.*_ga_XJWPQMJYHQ*czE3NDk0NDc3NjMkbzMkZzEkdDE3NDk0NDgxNDkkajU5JGwwJGgw